## Numpy array and basics 

In [2]:
import numpy as np

## Creating a new array

In [3]:
array_1d=np.array([1,2,3,4,5])
array_2d=np.array([[1,2,3],[3,4,5]])
print(array_1d)
print(array_2d)

[1 2 3 4 5]
[[1 2 3]
 [3 4 5]]


In [7]:
import time
start=time.time()
py_list=[i*2 for i in range(100000)]
print("list operation time is:",time.time()-start)

start=time.time()
np_aray=np.arange(100000)*4
print("numpt array operation time:",time.time()-start)

list operation time is: 0.011274576187133789
numpt array operation time: 0.0014379024505615234


## Creating Arrays from scratch

In [5]:
import numpy as np
zeros=np.zeros((3,4))
print("thee zero matrix is :",zeros)
ones=np.ones((3,2))
print("the ines matrix is:",ones)
full=np.full((3,4),5)
print("The full matrix is:",full)



thee zero matrix is : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
the ines matrix is: [[1. 1.]
 [1. 1.]
 [1. 1.]]
The full matrix is: [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [6]:
import numpy as np
tensor=np.array([[[[1,2],[2,3]],[[4,5],[6,7]]]])
print(tensor)

[[[[1 2]
   [2 3]]

  [[4 5]
   [6 7]]]]


## Array Properties 

In [10]:
import numpy as np
arr=np.array([1,2,34,5,6])
print("Dimension",arr.ndim)
print("shape",arr.shape)
print("size",arr.size)
print("Data Type",arr.dtype)

Dimension 1
shape (5,)
size 5
Data Type int64


## Array Reshaping

In [1]:
import numpy as np
arr=np.array([1,2,3,4,9,5,6,7,8,20,23,12])
reshaped=arr.reshape((3,4))
print("reshaped",reshaped)
flattened=arr.flatten()
print("flattened",flattened)
raveled=reshaped.ravel()
print("raveled",raveled)
transpose=reshaped.T
print("Transpose of a matrix:",transpose)


reshaped [[ 1  2  3  4]
 [ 9  5  6  7]
 [ 8 20 23 12]]
flattened [ 1  2  3  4  9  5  6  7  8 20 23 12]
raveled [ 1  2  3  4  9  5  6  7  8 20 23 12]
Transpose of a matrix: [[ 1  9  8]
 [ 2  5 20]
 [ 3  6 23]
 [ 4  7 12]]
