In [1]:
import numpy as np

In [5]:
arr=np.array([i for i in range(0,10)])
print("Original array:",arr)
print("array slicing:",arr[0:9:2])


Original array: [0 1 2 3 4 5 6 7 8 9]
array slicing: [0 2 4 6 8]


In [6]:
unsorted=np.array([5,2,8,1,9,3,4,0])
print("SORTED ARRAY:",np.sort(unsorted))

SORTED ARRAY: [0 1 2 3 4 5 8 9]


### Fnacy indexing vs np.where

In [10]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
indices=[1,3,5]
print(numbers[indices])
where_result=np.where(numbers>3)
print(where_result)
print("Np.where",numbers[where_result])
conditional=np.where(numbers>6,"true","false")
print(conditional)

[2 4 6]
(array([3, 4, 5, 6, 7, 8, 9]),)
Np.where [ 4  5  6  7  8  9 10]
['false' 'false' 'false' 'false' 'false' 'false' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [13]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
combined=arr1+arr2
print(combined)

[ 6  8 10]


In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9,10])
print("Compatibility check a and b:",a.shape==b.shape)
print("Compatibility check b abd c", b.shape==c.shape)

Compatibility check a and b: True
Compatibility check b abd c False


### Adding new row and column

In [20]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])
add_row=np.vstack((original,new_row))
new_col=([[8],[9]])
add_col=np.hstack((original,new_col))
print("original",original)
print("With new row",add_row)
print("With new col",add_col)

original [[1 2]
 [3 4]]
With new row [[1 2]
 [3 4]
 [5 6]]
With new col [[1 2 8]
 [3 4 9]]
